### ISSUE TITLE
Question: Where do you get your Fallout 76 weapon data?

### ISSUE THREAD

**Issue by jambolo** [akarnokd/rng-76#4]
I have looked around for Fallout 76 databases and haven't found any weapon data other than yours. Can you tell me how you obtain your data? Ideally, extraction would be an automated process so that it can be updated regularly and easily with no errors.

**Comment by akarnokd** [comment]
It has been a manual process of looking at the ingame weapon card, mod screen, weapon curve tables in the datafiles and nukacrypt's search function for the application effects of perks and buffs.

The weapons and mod descriptions in the datafiles are quite complicated. So much so that one would most likely have to rewrite part of the game's engine to get numbers out of it.

**Comment by jambolo** [comment]
You might be interested in taking a look at [my repo](https://github.com/jambolo/fallout76), specifically the code that converts the weapon data scraped from https://fallout.fandom.com/wiki/Fallout_76_weapons to JSON and the results. It might be helpful to compare the two sets of data.

**Comment by nassy93** [comment]
Not sure if it is a bug or a recent change but I would like to add i unlocked the perforating mag mod for the 10mm SMG by scrapping yesterday, It is shown as learnable for the 10mm smg on https://fallout.fandom.com/wiki/Perforating_magazine but https://fallout.fandom.com/wiki/10mm_submachine_gun_(Fallout_76) makes no mention of the perforating mag.
The damage calculator also does not seem to have the mag as an option.

**Comment by akarnokd** [comment]
I don't know. https://nukacrypt.com/database/json/00040891 does list it. I updated the definitions for the 10mm SMG and the Old Guard's.
